title: Kexun Shen
description: Plasma Physics 
author:
  name: 沈可勋
  avatar: photo1.jpg
  email: kxshen10@zju.edu.cn
  links:
    - label: Google Scholar
      icon: fab fa-google-scholar
      url: https://scholar.google.com/citations?user=PKmlMXkAAAAJ&hl=en
    - label: ORCID
      icon: fab fa-orcid
      url: https://orcid.org/0000-0002-0512-6273
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
