title: Kexun Shen
description: Plasma Physics 
author:
  name: Kexun Shen
  email: kxshen10@zju.edu.cn
  links:
    - label: Google Scholar
      icon: fab fa-google-scholar
      url: https://scholar.google.com/...
    - label: ORCID
      icon: fab fa-orcid
      url: https://orcid.org/...
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
