title: Kexun Shen
description:  
author:
  name: 沈可勋
  avatar: photo1.jpg
  email: kxshen10@zju.edu.cn
  bio: "Nonlinear Phenomena and Statistical Mechanics in Plasma Physics | PhD Student in Zhejiang University"
  location: "Hangzhou, Zhejiang, PRC"
  links:
    - label: Google Scholar
      icon: fab fa-google-scholar
      url: https://scholar.google.com/citations?user=PKmlMXkAAAAJ&hl=en
    - label: ORCID
      icon: fab fa-orcid
      url: https://orcid.org/0000-0002-0512-6273
markdown: kramdown
kramdown:
  math_engine: mathjax
remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: "mint"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
